apiVersion: 1

datasources:
  - name: ClickHouse
    uid: ael9uo16mu7lsd
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false

    jsonData:
      server: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: default
      username: default
      tlsSkipVerify: true
      secureJsonData:
        password: default