services:

  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile:ro
    ports:
      - "8153:53/udp"
      - "8153:53/tcp"

  fluent-bit-agent:
    image: fluent/fluent-bit:latest
    container_name: fb-agent
    restart: unless-stopped
    depends_on:
      - coredns
    volumes:
      - ./fluent-bit/agent.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: ["-c", "/fluent-bit/etc/fluent-bit.conf"]

  ml-model:
    build: ./ml-model
    container_name: ml-model
    restart: unless-stopped
    depends_on:
      - fluent-bit-agent
      - clickhouse
    ports:
      - "5000:5000"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=default
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse:/docker-entrypoint-initdb.d
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/default-password.xml:ro

  test-client:
    build: ./test-client
    container_name: test-client
    stdin_open: true
    tty: true
    depends_on:
      - coredns

volumes:
  clickhouse-data: