{
 "title": "New new new new dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "DNS requests over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(log_time) AS time,\r\n  COUNT(*) AS dns_requests\r\nFROM dns_logs\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  'Malicious' AS label,\r\n  COUNT(*) AS count\r\nFROM dns_logs\r\nWHERE\r\n  prediction = 1\r\n  AND $__timeFilter(log_time)\r\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  'Benign' AS label,\r\n  COUNT(*) AS count\r\nFROM dns_logs\r\nWHERE\r\n  prediction = 0\r\n  AND $__timeFilter(log_time)"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  protocol,\r\n  COUNT(*) AS request_count\r\nFROM\r\n  dns_logs\r\nWHERE\r\n  $__timeFilter(log_time)\r\nGROUP BY\r\n  protocol\r\nORDER BY\r\n  request_count DESC;"
    }
   ]
  },
  {
   "title": "Highest response time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  domain,\r\n  MAX(response_time) AS max_response_time\r\nFROM dns_logs\r\nWHERE $__timeFilter(log_time)\r\nGROUP BY domain\r\nORDER BY max_response_time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT domain, log_time, prediction, malicious_probability\r\nFROM dns_logs\r\nORDER BY log_time DESC;\r\n"
    }
   ]
  },
  {
   "title": "Malicious probability",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    domain,\r\n    MAX(malicious_probability) AS highest_malicious_probability\r\nFROM dns_logs\r\nWHERE malicious_probability > 0.0\r\n  AND $__timeFilter(log_time)\r\nGROUP BY domain\r\nORDER BY highest_malicious_probability DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Top domains",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  domain,\r\n  COUNT(*) AS requests\r\nFROM dns_logs\r\nWHERE $__timeFilter(log_time)\r\nGROUP BY domain\r\nORDER BY requests DESC\r\nLIMIT 10;\r\n"
    }
   ]
  }
 ]
}